### ISSUE TITLE
Building with nix

### ISSUE THREAD

**Issue by locallycompact** [expipiplus1/vulkan#139]
Hi, what is the intended way to build using the default.nix files in the library? If I do a nix-build or nix-shell from the root it seems to attempt to build the whole of hackage.

**Comment by expipiplus1** [comment]
`default.nix { forShell = false; }` evaluates to an attribute set with one attribute for each of the following packages

- `vulkan`, the main package of this repository
- `VulkanMemoryAllocator`, bindings to VMA
- `vulkan-utils`, a small selection of utility functions for using `vulkan`
- `vulkan-examples`, some examples, this package is dependency-heavy
- `generate-new`, the program to generate the source of `vulkan` and `VulkanMemoryAllocator`, also quite dependency-heavy (this only build with ghc 8.8).

You may want to pass `<nixpkgs>` as `pkgs` to `default.nix` to avoid rebuilding a parallel set of haskell packages based on the pegged nixpkgs version in `default.nix`. It should probably work with a wide range of nixpkgss, however some overrides in `default.nix` may need tweaking.

`nix-build -A vulkan` is probably not terribly useful for using the library as it just builds the haskell library.

`nix-build -A vulkan-examples` will produce a path with several examples, however to run these on a non-NixOS platform you'll need to use the [`NixGL`](https://github.com/guibou/nixGL) project (or something similar) to run these. This isn't something tested very often so may be a little fragile. I'd suggest for non-NixOS platforms compiling without using Nix (or better yet get reliable instructions for using `NixGL` and open a PR). 

This library is currently up to date on nixpkgs master, so if you're just a consumer it might be best to use it from a recent version there.

For using this repository, I have two workflows:

- For building and running examples
  - I navigate to the examples directory and use the `default.nix` expression in there to provision a shell with the correct dependencies for the examples.
  - I also make a `cabal.project` containing `packages: ./`, the reason for this little dance instead of just using the root's `default.nix` is so that nix builds the hoogle database for the dependencies and HIE's completion and indexing works much better for external dependencies instead of using a multi-package project as is the root.
  - This will override nixpkgs's `vulkan` and `VulkanMemoryAllocator` libraries with the ones in the repo, as well as building `vulkan-utils.

- For modifying the generation program I navigate to the `generate-new` directory and run `nix-shell ..` to use `default.nix` in the repo's root to provision a shell with:
  - The dependencies for running the generator
  - And the dependencies for compiling the `vulkan` source it spits out.
  - I run the generator with `ghci $(HIE_BIOS_OUTPUT=/dev/stdout ./flags.sh $(pwd)/vk/Main.hs) vk/Main.hs +RTS -N16`

**Comment by expipiplus1** [comment]
@locallycompact I added my comment to the project readme, happy to make changes or clarifications if anything's not clear.

**Comment by expipiplus1** [comment]
Oh, if you trust me and Cachix you could use https://app.cachix.org/cache/vulkan-haskell to avoid building all the dependencies, it should be kept warm by the CI on this repo.

**Comment by locallycompact** [comment]
Thanks for all this. A few things. It doesn't seem like vulkan-utils is in mainline nixpkgs. Basically I was hoping to depend directly on this repo for a shell to run the offscreen example headlessly in CI. If I try this directly from nixpkgs I get this:

```
> nix-shell -p 'haskellPackages.ghcWithPackages(ps: with ps; [vulkan VulkanMemoryAllocator mtl safe-exceptions say vulkan-utils])'
error: undefined variable 'vulkan-utils' at (string):1:193
(use '--show-trace' to show detailed location information)
```

My current state of the world is in this branch: https://gitlab.com/shakebook-site/shakebook-site.gitlab.io/-/tree/staging/nix

Since stack-to-nix won't work for this repo I wanted to proof of concept the idea of having a separate vulkan-nix.shell that just provides enough to build the offscreen example. In general I can't figure out how to merge the ghc shells of a stack-to-nix shellFor with a nixpkgs ghcWithPackages, if that's even possible, so a separate shell just for that build rule would suffice. Maybe there's an incantation for that you can help me out with.

The runner isn't NixOS currently but I'm happy to assume NixOS and change the runner.

**Comment by expipiplus1** [comment]
`examples/default.nix` is pretty much what you want for `vulkan-shell.nix` I think.

`vulkan-utils` is not in Hackage yet (and hence not in nixpkgs), you'd need to add it as an override in `haskellPackages`. The easiest way would be something like `vulkan-utils = callCabal2nix "" /path/to/vulkan/utils {};` (like here: https://github.com/expipiplus1/vulkan/blob/c04e412c35265f76ebb2f6808132798bf47e7910/examples/default.nix#L39-L41).

For an incantation to run the offscreen example, this works for me: `nix-shell examples --run 'cd examples && cabal run offscreen', That should build precisely what's necessary to enter a shell for the examples.

I'm not familiar with stack-to-nix, but I don't think there's anything terribly exotic in this repo which would prohibit it from working; no idea about combining shells either I'm afraid, but it smells non-trivial.

**Comment by expipiplus1** [comment]
Of course the dependencies put into the shell by `examples/default.nix` are just those to build the example project, if you want other dependencies you can change the expression here: https://github.com/expipiplus1/vulkan/blob/c04e412c35265f76ebb2f6808132798bf47e7910/examples/default.nix#L72-L73

**Comment by locallycompact** [comment]
I mean an incantation to call this repository and make a shell that could build examples elsewhere, not build the example in this repository from within this repository.

**Comment by locallycompact** [comment]
Sorry I get it now, I didn't understand what was being said.

What's the type of this thing so I can get rid of it and make it a trivial value? I don't want anything in the cabal, just vulkan and dependencies.

```
(haskellPackages.callCabal2nixWithOptions "" src "--flag=renderdoc" { });
```

**Comment by locallycompact** [comment]
This type checks but still seems to be building all of hackage (conduit, csv, aeson)

```
{ sources ? import ./nix/sources.nix {}
, pkgs ? import sources.nixpkgs {} }:
let
  vulkan = import sources.vulkan { forShell = false; };
  haskellPackages = with pkgs.haskell.lib;
    pkgs.haskellPackages.override {
      overrides = self: super:
        {
          vulkan-utils = vulkan.vulkan-utils;
        };
    };
in
  haskellPackages.ghcWithPackages(ps: with ps; [vulkan-utils])
```

**Comment by expipiplus1** [comment]
Ah, the reason it depends on heaps of things is because it's trying to build hpack (necessary for callCabal2nix):

![image](https://user-images.githubusercontent.com/857308/86423106-79931f00-bd11-11ea-84cb-c2eed3ec7995.png)

The reason that it builds things again (I assume you have hpack cached for your `./nix/sources.nix`) is because `sources.vulkan.vulkan-utils` is still using the package set pinned in this repo's default.nix. Even if you were to pass 'sources.nixpkgs' it wouldn't be the correct thing to do, because vulkan-utils would be being sourced from the `haskellPackages` overrides described in this repo's default.nix, and not in your nix expression. As an example, if you were to override `bytestring` in your `haskellPackages`, that new version wouldn't be included in `vulkan.vulkan-utils`, hence it would probably fail because two different versions of bytestring would be in the dependencies.

I would suggest something like

```nix
{ sources ? import ./nix/sources.nix {}
, pkgs ? import sources.nixpkgs {} }:
let
  vulkan = import sources.vulkan { forShell = false; };
  haskellPackages = with pkgs.haskell.lib;
    pkgs.haskellPackages.override {
      overrides = self: super:
        {
          vulkan-utils = addExtraLibrary (doHaddock
            (self.callCabal2nix "" (sources.vulkan + "/utils") { }))
            pkgs.vulkan-headers;
        };
    };
in
  haskellPackages.ghcWithPackages(ps: with ps; [vulkan-utils])
```

This still depends on hpack, but now it will be using the version from `sources.nixpkgs` instead of the pinned version in this repo.

**Comment by locallycompact** [comment]
Ah, OK that makes sense. It looks like vulkan has been marked as broken recently in nixpkgs.

```
lc@aiur ~/S/g/s/shakebook-site.gitlab.io (staging/nix)> nix-shell vulkan-shell.nix
unpacking 'https://github.com/expipiplus1/vulkan/archive/9f36bddc1956f07d2a6bed7a32894ef44f710514.tar.gz'...
building '/nix/store/s9zgds23v3mxlpr6rx2yhbzq1sxz8gh8-cabal2nix-.drv'...
installing
*** found package.yaml. Using hpack...
error: Package ‘vulkan-2.1.0.0’ in /nix/store/08xfivmynisgv4lxp4d9x457x8a1qhcp-source/pkgs/development/haskell-modules/hackage-packages.nix:246661 is marked as broken, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

**Comment by expipiplus1** [comment]
Ah, 2.1 is ancient. I think 3.5 (the latest version) was merged to master
about 10 days ago.

You could always override vulkan in the same way as adding vulkan-utils in
the expression in my last comment (vma too).

**Comment by expipiplus1** [comment]
So probably something like this would be best. Perhaps this should be extracted into a separate nix file in this repo.

```nix
      haskellPackagesOverrides = self: super: {
        vulkan = doHaddock (self.callCabal2nix "vulkan" sources.vulkan {
          vulkan = pkgs.vulkan-loader;
        });
        vulkan-utils = addExtraLibrary
          (doHaddock (self.callCabal2nix "" (sources.vulkan + "/utils") { }))
          pkgs.vulkan-headers;
        VulkanMemoryAllocator = addExtraLibrary (doHaddock
          (self.callCabal2nix "" (sources.vulkan + "/VulkanMemoryAllocator")
            { })) pkgs.vulkan-headers;

        # SDL2 vulkan support was broken before 2.5.2.0
        # https://github.com/haskell-game/sdl2/pull/209
        sdl2 = overrideSrc super.sdl2 {
          src = pkgs.fetchFromGitHub {
            owner = "haskell-game";
            repo = "sdl2";
            rev = "d10b2ae86ce3db58c5c011cbec6eccf69c2fd2f1";
            sha256 = "1qfjfrzc9yjg8ibgr0a7fly6fnd1f2yv731n7h1wjgz9vaa3q6wg";
          };
        };
      };
```

**Comment by expipiplus1** [comment]
Adding a recent `autoapply` is useful, it's used in most of the examples to reduce some boilerplate

https://github.com/expipiplus1/vulkan/blob/c04e412c35265f76ebb2f6808132798bf47e7910/examples/default.nix#L19-L30 should do it

**Comment by expipiplus1** [comment]
Please reopen if it's still not working.

**Comment by locallycompact** [comment]
The vulkan stuff is working with that snippet you posted but autoapply is failing due to https://github.com/expipiplus1/autoapply/pull/3

**Comment by expipiplus1** [comment]
Yeah, autoapply is ghc 8.8+. Sadly it's not as simple as just reenabling
the tests. Would be happy to accept a PR getting it working on 8.6 though.

**Comment by locallycompact** [comment]
Ok I'm getting the header not found error again. This is what I have so far.

```
{ sources ? import ./nix/sources.nix {}
, pkgs ? import sources.nixpkgs {} }:
let
  haskellPackages = with pkgs.haskell.lib;
  pkgs.haskell.packages.ghc8101.override {
    overrides = self: super: {
      vulkan-utils = addExtraLibrary
          (doHaddock (self.callCabal2nix "" (sources.vulkan + "/utils") { }))
          pkgs.vulkan-headers;
      VulkanMemoryAllocator = addExtraLibrary (doHaddock
        (self.callCabal2nix "" (sources.vulkan + "/VulkanMemoryAllocator")
          { })) pkgs.vulkan-headers;
      vulkan = doHaddock (self.callCabal2nix "vulkan" sources.vulkan {
        vulkan = pkgs.vulkan-loader;
      });
      th-desugar = self.callCabal2nix "" (pkgs.fetchFromGitHub {
        owner = "goldfirere";
        repo = "th-desugar";
        rev = "f075206882ce4e554c37537e624b4be7409d74a3";
        sha256 = "0747xggx2q8yphag2wv06dj0pgi9zvadi069c2d6lckg26chhnlk";
      }) { };
      th-orphans = self.callCabal2nix "" (pkgs.fetchFromGitHub {
        owner = "mgsloan";
        repo = "th-orphans";
        rev = "713b4e14890b856b52a5f9f57e0cd06d99c5195b";
        sha256 = "0482j056nxf7bns4qzkkv40gi61f2z5jnyg1d5ks1l01gjfdrqkp";
      }) { };
      autoapply = doHaddock (self.callCabal2nix "" (pkgs.fetchFromGitHub {
        owner = "expipiplus1";
        repo = "autoapply";
        rev = "4ff481b28c9f2b081496593bba491633873ca155";
        sha256 = "0hfcx9mnan0f5h5x8qvpzybbvn6brmia7s2wfgk8j61arghfwg8k";
      }) { });
    };
  };
in
  haskellPackages.ghcWithPackages(ps: with ps; [vulkan-utils vulkan VulkanMemoryAllocator autoapply])
```

```
src/lib.cpp:9:10: error:
     fatal error: vk_mem_alloc.h: No such file or directory
        9 | #include <vk_mem_alloc.h>
          |          ^~~~~~~~~~~~~~~~
  |
9 | #include <vk_mem_alloc.h>
  |          ^
compilation terminated.
`cc' failed in phase `C Compiler'. (Exit code: 1)
builder for '/nix/store/q4xld6cyq8afnpbz2h31k8dqkxdqwln1-VulkanMemoryAllocator-0.3.3.drv' failed with exit code 1
error: build of '/nix/store/q4xld6cyq8afnpbz2h31k8dqkxdqwln1-VulkanMemoryAllocator-0.3.3.drv' failed
```

**Comment by expipiplus1** [comment]
looks like the same issue as https://github.com/expipiplus1/vulkan/issues/119, I guess that `sources.vulkan` isn't cloning the submodules.
