### ISSUE TITLE
sdl-triangle example uses 100% CPU in some window managers

### ISSUE THREAD

**Issue by expipiplus1** [expipiplus1/vulkan#231]
Nvidia 1060, fvwm2

CC @int-e

**Comment by int-e** [comment]
The main loop of this program is a tight loop that alternates between calling `SDL.pollEvents` and drawing another frame. On my system configuration that is (apparently) enough to saturate a CPU core, and also keep the GPU so busy that X11 becomes almost unresponsive. Here's the relevant code:
```haskell
mainLoop :: IO () -> IO ()
mainLoop draw = whileM $ do
  quit <- Prelude.any isQuitEvent <$> SDL.pollEvents
  if quit
    then pure False
    else do
      draw
      pure True
```
A possible solution is to wait for an actual event to happen instead of waiting busily (this could be refined to look for redraw and resize events exclusively).

(The same analysis applies to `resize`, but somehow, it does not overload my system in the same way. Still, it continues to render the window even when the mouse hasn't moved, so there's room for improvement.)
