### ISSUE TITLE
More maintainers

### ISSUE THREAD

**Issue by expipiplus1** [expipiplus1/vulkan#259]
@dpwiz, @sheaf, (or anyone else interested):

Do you want write access to this repo and to `vulkan` on Hackage? For merging api version bumps or any other changes you want.

I think it's pretty low work, every so often the bot will open a PR bumping the api version like this: https://github.com/expipiplus1/vulkan/pull/247, just comment `/bump vulkan=minor` (if there aren't breaking changes obv) and merge. Another bot will watch version numbers for changes and push tags, and another bot watches for tags and then makes a github release. (The version bumping bot is broken at the moment as it's partially hosted from my (down) home server). Once a github release is made then one can release to hackage with this code:

```bash
tag=v3.9.1
hub release download refs/tags/$tag |
  cut -d' ' -f2 |
  sort -r |
  while read f; do
    if [[ "$f" =~ "-docs.tar.gz" ]]; then
      cabal upload --publish --doc "$f"
    else
      cabal upload --publish "$f"
    fi
    rm "$f"
  done
```

I have no plans to stop maintaining this, but life happens sometimes and it'd be good to have other people around.

**Comment by sheaf** [comment]
It sounds like you have it set up nicely, whereas it'd take me a bit to get familiar enough to be confident I wouldn't accidentally mess things up, or be able to fix the occasional problem. I'm happy to give it a go though; you've provided straightforward instructions after all. (I haven't done much Vulkan the past few weeks, but when I get back into it, I'll likely have some contributions to make.)

Anyway, I think you've been doing a stellar job maintaining (and writing!) the library, and I don't want you to be made to worry in any way because of maintenance.

**Comment by dpwiz** [comment]
> Nice package you've got here. It will be a pity if something bad happens to it 😄

I will be honored to dive in and get to know more about keeping it in good shape.

**Comment by expipiplus1** [comment]
Cool, invites sent here and on Hackage. No obligation or expectations :)
